name: C/C++ CI (Windows)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Premake
      uses: abel0b/setup-premake@v2.4
      with:
        version: "5.0.0-beta2"

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Generate Visual Studio Project with Premake
      run: premake5 --file=Build.lua vs2022

    - name: Download Precompiled GLFW
      run: |
        curl -L -o glfw.zip https://github.com/glfw/glfw/releases/download/3.4.0/glfw-3.4.0.bin.WIN64.zip
        tar -xf glfw.zip
        copy glfw-3.4.0.bin.WIN64\lib-vc2022\glfw3.lib D:\a\RED\RED\Libraries\glfw-3.4

    - name: Clean Build Directory
      run: msbuild RED.sln -t:clean -verbosity:minimal

    - name: Build app for Release (x64)
      run: msbuild RED.sln -t:rebuild -verbosity:diag -property:Configuration=Release -property:Platform=x64

    - name: Debug Environment
      run: |
        dir D:\a\RED\RED\Libraries\glfw-3.4
        dir D:\a\RED\RED\Libraries\vulkan
        echo %PATH%

    - name: Run Tests
      run: |
        cd bin\Release
        MyTests.exe

    - name: Verify Distribution Build
      run: |
        cd bin\Release
        MyExecutable.exe --distcheck
