name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: abel0b/setup-premake@v2.4
      with:
        version: "5.0.0-beta2"

    - name: Generate Makefiles with Premake
      run: premake5 --file=Build.lua gmake2

    - name: Build Project
      run: make

    - name: Run Tests
      run: make check

    - name: Verify Distribution Build
      run: make distcheck
