name: C/C++ Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install System Dependencies
      run: sudo apt-get update && sudo apt-get install -y mesa-common-dev libgl1-mesa-dev

    - name: Install Wayland Dependencies
      run: sudo apt-get update && sudo apt-get install -y wayland-protocols wayland-devel


    - name: Clean Previous Build
      run: rm -rf ./Libraries/glfw-3.4/build ./Libraries/glfw-3.4/CMakeCache.txt

    - name: Build and Install GLFW
      run: |
        cd ./Libraries/glfw-3.4
        cmake -Bbuild -H. -DBUILD_SHARED_LIBS=ON
        make -C build
        sudo make install

    - uses: abel0b/setup-premake@v2.4
      with:
        version: "5.0.0-beta2"

    - name: Generate Makefiles with Premake
      run: premake5 --file=Build.lua gmake2

    - name: Build Project
      run: make
