name: Linux build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: update
      run: sudo apt update
    - name: glfw dependencies
      run: sudo apt install libwayland-dev libxkbcommon-dev xorg-dev
    - name: install other dependencies
      run: sudo apt-get install g++ build-essential libgl1-mesa-dev libpng-dev
    - name: give permissions
      run: sudo chmod +x Vendor/Binaries/Premake/Linux/premake5 && sudo chmod +x Scripts/Setup-Linux.sh
    - name: build premake
      run : cd Scripts && ./Setup-Linux.sh
    - name: make
      run: ls && make
