name: Linux Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Update apt
        run: sudo apt update

      - name: Install GLFW dependencies
        run: sudo apt install -y libwayland-dev libxkbcommon-dev xorg-dev

      - name: Install build dependencies
        run: sudo apt install -y g++ build-essential cmake ninja-build libgl1-mesa-dev libpng-dev libbz2-dev

      - name: Configure (Release)
        run: |
          cmake -S . -B cmake-build-release \
                -G Ninja \
                -DCMAKE_BUILD_TYPE=Release

      - name: Build Editor
        run: cmake --build cmake-build-release --target Editor --parallel

      - name: Build Game
        run: cmake --build cmake-build-release --target Game --parallel

      - name: Archive Editor artifact
        uses: actions/upload-artifact@v4
        with:
          name: Editor-Linux
          path: Binaries/linux-x86_64/Release/Editor/Editor

      - name: Archive Game artifact
        uses: actions/upload-artifact@v4
        with:
          name: Game-Linux
          path: Binaries/linux-x86_64/Release/Game/Game